### ISSUE TITLE
Create dmg from packed app

### ISSUE THREAD

**Issue by steffenmllr** [nwjs/grunt-nw-builder#1]
Use https://github.com/andreyvit/yoursway-create-dmg to create a dmg on the fly

**Comment by Yimiprod** [comment]
there is something like this:
https://github.com/rakuten-frontend/grunt-appdmg
by the way there is the windows pendant:
https://github.com/ralucas/grunt-makensis

**Comment by adam-lynch** [comment]
This can only run on OS X, so we can't :/
