### ISSUE TITLE
"Fatal error: EMFILE, open" when building osx distribution

### ISSUE THREAD

**Issue by kiyanwang** [nwjs/grunt-nw-builder#103]
I'm using grunt-node-webkit-builder my config looks like this : 

```
nodewebkit: {
      options: {
        version: "0.10.0",
        buildDir: './dist',
        // specifiy what to build
        platforms:['osx','win','linux32','linux64'],
        macIcns: './nw.icns',
        macZip: false
        ,win_ico: './nw.ico'
      },
      src: './_public/**/*'
    },
```

This worked fine whilst my _public folder (the node-webkit app ive written) did not contain a node_modules folder. However as soon as I include a node_modules folder I get this error:

```
Fatal error: EMFILE, open '/Users/nadeemshabir/Development/projects/desktop_apps/talis-uploader-desktop-app/_public/node_modules/request/node_modules/hawk/node_modules/hoek/package.json'.
```

It only errors for the OSX distribution, the others work fine.
I'm on Mavericks, running grunt-node-webkit-builder 0.2.1 which is using node-webkit-builder 0.1.1.

Also If I dont include the node_modules folder in the _public directory, then use the the grunt task to build the distribution it works, if I then manually copy the node_modules folder into `/Contents/Resources/app.nw/` in the dist folder, and run the app the app works perfectly. So I have a work around. 

Any thoughts on how I can prevent that error?

**Comment by flocca** [comment]
Thanks @mudcube, setting macZip to true solves the issue.

So there are two different issue: one that can be solved using `ulimit -n 1024` and this one @adam-lynch.
