### ISSUE TITLE
v0.10.2 issue

### ISSUE THREAD

**Issue by matt-imgd** [nwjs/grunt-nw-builder#104]
I've the following configuration in my Gruntfile.js:

 nodewebkit: {
      options: {
        version: '0.10.2',
        platforms: ['win', 'osx', 'linux32', 'linux64'],
        buildDir: './webkitbuilds'
      },
      src: ['./dist/**/*']
    },

But when I run the Grunt task it fails with:

Fatal error: ENOENT, no such file or directory '/home/matt/myproject/src/nw/cache/0.10.2/linux32/nw'

I checked the "cache" folder, and I think the NodeWebkit v0.10.2 ".tar.gz" files has different structure than the previous version

Could you check and fix this one?

**Comment by adam-lynch** [comment]
I'm embarrassed no one got back to you on this. If its any consolation; as of today, grunt-nw-builder and nw-builder now support all newer versions, alpha/beta builds, and have gotten a few things fixed, etc.
