### ISSUE TITLE
Issue with Mac icon

### ISSUE THREAD

**Issue by jwoertink** [nwjs/grunt-nw-builder#106]
When I build just the osx package, my icon shows up fine, but if I build both osx and win packages together, the win icon shows up fine, but the osx icon shows up as the default node-webkit icon. Here is my Gruntfile.js

```javascript
module.exports = function(grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    nodewebkit: {
      options: {
        version: '0.10.3',
        buildDir: './build',
        platforms: ['win', 'osx'],
        appName: 'ALICE Client',
        appVersion: '0.0.1',
        winIco: './webarc.nw/alice.ico',
        macIcns: './webarc.nw/alice.icns'
      },
      src: ['./webarc.nw/**']
    }
  });

  grunt.loadNpmTasks('grunt-node-webkit-builder');
  grunt.registerTask('default', ['nodewebkit']);
};

```
using version `0.2.2` on OSX 10.9.4
Is there something I'm missing?

**Comment by adam-lynch** [comment]
Some fixes were made around this. Should be ok with the latest version. Thanks for reporting.
