### ISSUE TITLE
Building with many files is very slow

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [nwjs/grunt-nw-builder#109]
I want to start off by saying this: I am not 100% sure if this is an issue with grunt-node-webkit-builder, or node-webkit-builder. 

I recently updated to grunt-node-webkit-builder -v 0.2.3 from 0.1.14 (on osx).

What I noticed is that there is a MASSIVE decrease in performance when I am building my application :( 

My nodewebkit app have quite a lot of files (roughly 50 000) mostly due to some external libraries I am using. Building the app now takes way, way longer than it did on 0.1.14. Even when I try to remove all the external libraries, so the file-count is drastically reduced (roughly 150), the building process is slower than what it was before, even when I was including the external libraries.

I am also getting EMFILE-issues, which [I have found is due to too low ulimit](https://github.com/gruntjs/grunt/issues/788). So my app is currently not being fully built either.

The reason why I updated grunt-node-webkit-builder was that for some reason I could not get nodewebkit -v 0.10.5 to work with version 0.1.14 of grunt-node-webkit-builder. 

What should I do? Any help?

Also: I apologise if this issue should have be posted in node-webkit-builder. I am not really sure what part of the system is hanging.

**Comment by estvmachine** [comment]
You can try build your app without the node_modules and other libraries. Then when you created your app, put the external libraries in the same root.

**Comment by adam-lynch** [comment]
Should be faster with changes made in https://github.com/nwjs/nw-builder/pull/333. Thanks.
