### ISSUE TITLE
Getting placeholder content in app instead of my actual web app

### ISSUE THREAD

**Issue by protozoo** [nwjs/grunt-nw-builder#123]
Hi,

I'm trying to compile an app using grunt-node-webkit-builder without success.
Looks like my source files (the actual web app I want to convert into a native app) are not included, since when I run the compiled file it will show just webkit window with text "NODE-WEBKIT" in ASCII art.

I tried manually compressing my web app, renaming to myapp.nw, and dragging this file onto the node-webkit binary. If I do it like this, the web-app shows just fine.

Any ideas on what the problem can be?

Thanks

**Comment by IvanSanchez** [comment]
I'm having a similar problem.

I'm the developerof https://github.com/IvanSanchez/artemis-glitter , and it builds binary packages via `grunt-node-webkit-builder`. I develop and build on a linux64 computer.

The linux builds work just fine. I haven't been able to test out the OSX builds. However, the windows builds fail.

An interesting symptom: in the linux build, I can see a URL with a temp directory and my entry HTML page and everything works. In the windows build, the URL is `nw:blank`.

Having "nw:blank" on the URL bar means I get "node-webkit" on ascii-art when I tell `grunt-node-webkit-builder` to use `node-webkit` 0.11.x, or "NW.JS" on a grey background when I tell it to use 0.12-alpha (AKA "latest").

If I move the `.exe` file to a directory containing a clone of my git repo (i.e. the `.exe` and `package.json` and the entry HTML are in the same directory) it seems to load, but the console shows `Uncaught Error: Cannot find module 'depd'`.

I have tried tweaking my gruntfile, using different versions of node-webkit and clearing the cache and build dirs a dozen times with no effect.

**Comment by daffingtons** [comment]
I think this is the same issue I'm having (on OSX, module version 1.0.8.)

I've tried clearing the cache & using different module versions, but it seems like the same issue as above. I'm quite new to node-webkit so it's likely that I've screwed up somehow

**Comment by adam-lynch** [comment]
I think this was most likely paths which were too long for Windows (> 256). Typically this is caused by a really deep `node_modules` structure. Using npm 3+ would resolve this since it tries to flatten your dependencies.
