### ISSUE TITLE
Fatal error: Error: ENFILE

### ISSUE THREAD

**Issue by arthurakay** [nwjs/grunt-nw-builder#131]
I consistently hit the following error on OSX running Yosemity:

```
Running "nodewebkit:src" (nodewebkit) task
Latest Version: v0.12.0
Using v0.12.0
Create cache folder in /Users/arthurakay/www/XYZ/cache/0.12.0
Using cache for: osx32
Create cache folder in /Users/arthurakay/www/XYZ/cache/0.12.0
Using cache for: osx64
Create release folder in /Users/arthurakay/www/XYZ/dist/MY APP/osx32
Create release folder in /Users/arthurakay/www/XYZ/dist/My APP/osx64
Fatal error: Error: ENFILE, open '/Users/arthurakay/www/XYZ/dist/MY APP/osx64/MY APP.app/Contents/Resources/app.nw/node_modules/node-webkit-builder/node_modules/decompress-zip/node_modules/mkpath/mkpath.js'
```

Oddly enough, the file throwing the error will change randomly -- but the error itself does not. Therefore I am wondering if it is related to [this issue](https://github.com/mllrsohn/node-webkit-builder/issues/180) from `node-webkit-builder`, where the async file copies are causing issues.

Running `ulimit -n` in my terminal gives me "2560" so I've set things about as high as I can. My project does contain a large number of files. Help?

**Comment by fmayer-tstllc** [comment]
According to http://www.gnu.org/software/libc/manual/html_node/Error-Codes.html, there are too many distinct file openings in the entire system.

**Comment by arthurakay** [comment]
I did find that by limiting the build to a single platform (e.g. OSX 64 bit) I can usually avoid the issue. But it does seem to me that perhaps doing sync file copies (rather than async) would completely avoid the issue.

**Comment by fmayer-tstllc** [comment]
Actually I got the issue with Karma when I include a lot of files, ~2500 is already enough to cause the problem. When I reduced the number of files by making my criteria more narrow, the issue went away.

**Comment by Sherlock92** [comment]
Also hitting this issue, osx yosemite.

**Comment by adam-lynch** [comment]
I haven't heard of this problem in a long long time. It should be ok now I think. Thanks for reporting.
