### ISSUE TITLE
downloadUrl option not working

### ISSUE THREAD

**Issue by watdafox** [nwjs/grunt-nw-builder#132]
We were previoulsy using `0.1.x` but need to move on to `>= 0.2.x` because of the icudtl.dat. The issue is: we can't download from a provided downloadUrl.

Error is:

```
Downloading: http://get.popcorntime.io/nw/v0.11.5/node-webkit-v0.11.5-win-ia32.zip
undefined
Fatal error: Unable to download nodewebkit.
```

Find complete gruntfile.js [here](https://git.popcorntime.io/popcorntime/desktop/blob/nw11/Gruntfile.js#L202).

Any ideas ? Thanks

**Comment by tom-axisj** [comment]
:+1:

**Comment by steffenmllr** [comment]
This is a bug related to `popcorntime`, please report the issue in their issue tracker

**Comment by watdafox** [comment]
I'm a member of Popcorn Time, and I'm asking here because I couldn't make it work :D

**Comment by watdafox** [comment]
Ok, the file must be named nwjs, not node-webkit. This is a lack of documentation, had to guess it;
