### ISSUE TITLE
Error: MODULE_NOT_FOUND for required modules

### ISSUE THREAD

**Issue by craigshoemaker** [nwjs/grunt-nw-builder#134]
When I run my application during development using the following command:

    nw.exe .

...everything works as expected and when I open the developer tools I see this:

![image](https://cloud.githubusercontent.com/assets/127797/7661645/5aa73b50-fb09-11e4-954b-22cdecbc8168.png)

However, when I attempt to run the application after running **grunt-node-webkit-builder**, I get the following errors:

![image](https://cloud.githubusercontent.com/assets/127797/7661655/73f5c108-fb09-11e4-87d1-1edc1204b068.png)

I understand that some modules that use [C/C++ addons may require a rebuild](https://github.com/nwjs/nw.js/wiki/Using-Node-modules#3rd-party-modules-with-cc-addons), but that's certainly not the case for [lodash](https://github.com/lodash/lodash) and [humanize-plus](https://github.com/HubSpot/humanize).

I have made my code available [in this repository so you can see what I am doing](https://github.com/craigshoemaker/grunt-node-webkit-builder-test). For quick reference, this is all the script is attempting to do:

``` javascript
(function () {

    var attemptRequire = function(moduleName){
        try {
            var mod = require(moduleName);
            console.log(moduleName + ' loaded');
        } catch (ex){
            console.log(ex);
        }
    };
    
    attemptRequire('underscore');
    attemptRequire('lodash');
    attemptRequire('humanize-plus');
    attemptRequire('fs');
    attemptRequire('fs-extra');
    attemptRequire('node-webkit-fdialogs');

}());
```

Any insight you can offer is appreciated.

**Comment by adam-lynch** [comment]
Sorry for taking so long to get to this. Those modules would exist in `/node_modules` but you don't tell grunt-nw-builder to put `node_modules` in your app. See https://github.com/craigshoemaker/grunt-node-webkit-builder-test/blob/master/gruntfile.js#L12.
