### ISSUE TITLE
Too much verbose when building

### ISSUE THREAD

**Issue by Yimiprod** [nwjs/grunt-nw-builder#140]
When i building my app i get a lot of log during the zip part, it return every file zipped for every build env. At the moment i build for mac and win, 32 and 64, so i get 4 zip message for each file zipped making the log too big and almost unreadable.

The download do something werd too:
```downloading [] 0% 0.0s  downloading [] 0% 11.3s  downloading [] 0% 14.1s  downloading [] 0% 13.9s  downloading [] 0% 20.5s```
 (only a partial of the log message), it repeat the message for every bits downloaded.

**Comment by adam-lynch** [comment]
>When i building my app i get a lot of log during the zip part, it return every file zipped for every build env. At the moment i build for mac and win, 32 and 64, so i get 4 zip message for each file zipped making the log too big and almost unreadable.

Hmm strange. Can you give me an example of the log?

>The download do something werd too:
downloading [] 0% 0.0s downloading [] 0% 11.3s downloading [] 0% 14.1s downloading [] 0% 13.9s downloading [] 0% 20.5s
>(only a partial of the log message), it repeat the message for every bits downloaded.

Weird. Are you on Windows?

**Comment by Yimiprod** [comment]
A travis with objective C env

**Comment by adam-lynch** [comment]
Sorry for taking so long to get to this. I guess this was a problem on Travis' side of things.
