### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by dalisoft** [nwjs/grunt-nw-builder#141]
Hi!
 i'm using started NodeWebkit.
But if i open nw.exe, opening Gruntfile.js. How i run page?

**Comment by dalisoft** [comment]
Someone seen this?

**Comment by adam-lynch** [comment]
Hmm. I'm not sure what's happening. Does your app work if you're using just the [official NW.js npm package (`nw`)](https://npmjs.org/package/nw) to run it?

**Comment by dalisoft** [comment]
Yes i using official

**Comment by adam-lynch** [comment]
What do you specify in your app manifest's `main` property? It should be your HTML file.
