### ISSUE TITLE
Icon of running application is not properly displayed (nwjs icon instead)

### ISSUE THREAD

**Issue by krisdante** [nwjs/grunt-nw-builder#142]
I added icon for Windows. It is properly displayed in File explorer but in application itself it is not.

![2015-08-19_152755](https://cloud.githubusercontent.com/assets/652384/9357847/6b0e6b6e-4689-11e5-90f6-34e538c39b1e.png)

Packaging was done on OSX. Runtime is Windows 10 x64

**Comment by adam-lynch** [comment]
I'm not 100% sure but I think this is the icon you specify in your app manifest. See https://github.com/nwjs/nw.js/wiki/Manifest-format#icon. Did you try that? :smile:

**Comment by krisdante** [comment]
Well this is how the icon was assigned to app (the one that you can see in Explorer). 
It is visible in explorer, but now for runnin process.

**Comment by adam-lynch** [comment]
Sorry I always get mixed up between the icons you have to give. So you gave a  `winIco` as well?

**Comment by krisdante** [comment]
```
var nw = new NwBuilder({
        files: [ './bower_components/**/**', './stylesheets/*.*', './app/**/**', 'ico/*', 'index.html', 'package.json', './sound/**' ],
        platforms: ['osx64', 'win64', 'linux64'],
        appName: 'creativedesk',
        //platforms: ['osx64'],
        appVersion: '0.61',
        cacheDir: './node_modules/nw-builder/cache',
        macZip: false,
        icon: './sysico/Task-List-icon.ico',
        winIco: './sysico/Task-List-icon.ico',
        macIcns: './sysico/Task-List-icon.icns',
        version: '0.12.3'
    });
```

**Comment by krisdante** [comment]
OK I was stupid. I specified that in Gulpfile instead of package property for window. I'll test that now. I think it works.

**Comment by krisdante** [comment]
That worked with PNG but not with ico file (and I would like to have optimised resolutions). Any hint how to improve that too ?

**Comment by adam-lynch** [comment]
@krisdante I'm not sure if that's possible. I just checked one of my own apps and I just give a large PNG (1024x1024).
