### ISSUE TITLE
Verifying property clean.build exists in config... ERROR

### ISSUE THREAD

**Issue by derekstavis** [nwjs/grunt-nw-builder#143]
I'm porting an existing project to use grunt-nw-builder. The Gruntfile has lots of stuff to compile the sources to `build` directory, where the production application stays after it's compiled.

I just copied the `initConfig` and the `loadNpmTasks` from this repo README and pasted accordingly to project structure and now when I run `grunt` it breaks with this message:

    Verifying property clean.build exists in config... ERROR

If I remove the `initConfig` it works. There should be something conflicting with my project structure. Any clues about that?

**Comment by adam-lynch** [comment]
Sorry, no I don't. I haven't used Grunt much myself. `clean.build` doesn't exist anywhere in this project though. So maybe you broke some of your own Grunt config?
