### ISSUE TITLE
Unable to Simultaneously Build for OSX and WIN Platforms

### ISSUE THREAD

**Issue by logitron** [nwjs/grunt-nw-builder#147]
I have a node project that I'm using grunt-nw-builder to build both an OSX and WIN version.  I noticed that, in my options, when I specify both 'osx' and 'win', I get an error:

`Fatal error: path must be a string`

If I only specify 'osx' or only specify 'win', it builds without any errors.  I've also tried doing things like ['osx32','osx64','win32',win64'] or ['osx32','win32'], etc.  No issues until I have both a 'win' and 'osx' in the same array.  Here is my non-working config:

    nwjs:
      options:
        version: '0.12.2'
        platforms: ['win','osx']
        buildDir: './build'
        appName: "SS#{ampModel}HD"
        winIco: 'tmp/favicon.ico'
        macIcns: 'tmp/favicon.icns'
      src: ['tmp/**/**/*']`

**Comment by wesleywesley** [comment]
Did you find the solution?

**Comment by ramiz4** [comment]
you need to set `zip: true` in options

**Comment by adam-lynch** [comment]
The zip option has been added. I think this should be OK now. Thanks.
