### ISSUE TITLE
Doesn't work with nwjs 0.13+

### ISSUE THREAD

**Issue by wb9688** [nwjs/grunt-nw-builder#148]
I tried this grunt task with nwjs 0.13.3 and it doesn't work, because nwjs uses different file(name)s since v0.13. I get the following error:

```
Fatal error: ENOENT: no such file or directory, lstat 'C:\path\to\my\nwjs\app\cache\0.13.3\win32\ffmpegsumo.dll'
```

**Comment by sswayney** [comment]
I have encountered the same issue. Any help?

**Comment by joshterrill** [comment]
This repo is only supported up to nwjs v0.11.5. I'll be putting in a pull request to update it for the newer versions. Check back in a day or two.

**Comment by adam-lynch** [comment]
Newer NW.js versions including alpha/beta builds are supported as of 2.0.1. Thanks for reporting. Let me know if there's any problem with the new version.
