### ISSUE TITLE
ERROR: The version 0.14.0-rc2 does not have a corresponding build

### ISSUE THREAD

**Issue by StokedIndustries** [nwjs/grunt-nw-builder#149]
I installed the plugin via npm and setup my package.json as instructed, then ran grunt nodewebkit. Midway through the process it stops and gives me this error:

ERROR: The version 0.14.0-rc2 does not have a corresponding build posted at http://dl.nwjs.io/. Please choose a version from that list.

How can I fix this? Or is it something that needs to be updated on the developers side to make it look for the correct package?

**Full error message:**

Electric-Frisbee:point-of-sale ryan$ grunt nodewebkit
Running "nodewebkit:src" (nodewebkit) task
Latest Version: v0.14.0-rc2
Using v0.14.0-rc2
Create cache folder in /Users/ryan/Repositories/point-of-sale/cache/0.14.0-rc2
Downloading: http://dl.nwjs.io/v0.14.0-rc2/nwjs-v0.14.0-rc2-win-ia32.zip
Create cache folder in /Users/ryan/Repositories/point-of-sale/cache/0.14.0-rc2
Downloading: http://dl.nwjs.io/v0.14.0-rc2/nwjs-v0.14.0-rc2-win-x64.zip
Create cache folder in /Users/ryan/Repositories/point-of-sale/cache/0.14.0-rc2
Downloading: http://dl.nwjs.io/v0.14.0-rc2/nwjs-v0.14.0-rc2-osx-ia32.zip
Create cache folder in /Users/ryan/Repositories/point-of-sale/cache/0.14.0-rc2
Downloading: http://dl.nwjs.io/v0.14.0-rc2/nwjs-v0.14.0-rc2-osx-x64.zip
  downloading [--------------------] 0% 640.5sERROR: The version 0.14.0-rc2 does not have a corresponding build posted at http://dl.nwjs.io/. Please choose a version from that list.
Fatal error: Unable to download nodewebkit.

Execution Time (2016-04-07 01:36:20 UTC)
nodewebkit:src  9.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 9.7s

**Comment by rogerwang** [comment]
The download URL is valid. Please report the issue to the correct project/repo.

**Comment by rogerwang** [comment]
oops. my bad...

**Comment by oskar-szulc** [comment]
You can fix it by replacing "osx" with "osx64" when adding platforms in you config file. Don't think osx32 is supported anymore.

**Comment by StokedIndustries** [comment]
Tried that, seems to get past the above errors. But now I get:

Fatal error: ENOENT: no such file or directory, lstat '/Users/ryan/Repositories/point-of-sale/cache/0.14.0-rc2/win64/ffmpegsumo.dll'

**Comment by hpcodecraft** [comment]
I'm running into the same error as @StokedIndustries does. Replacing 'osx' with 'osx64' and 'win' with 'win64' fixed the downloads, but now:

Fatal error: ENOENT: no such file or directory, lstat '/Users/volker.wieban/Projects/MyProject/dist/cache/0.14.2/win64/ffmpegsumo.dll'

Any ideas?

**Comment by adamhurst** [comment]
Take a look here: https://github.com/nwjs/nw-builder/blob/master/lib/platforms.js#L20

NW v0.14.x and v0.12.x are very different and nw-builder has not been updated to take into account the changes in v0.14. ffmpegsumo.dll is, for example, in v0.12.x but not in v0.14.x. I managed to get past the above error by setting the list of files to this:
[
	'd3dcompiler_47.dll',
	'dbghelp.dll',
	'ffmpeg.dll',
	'icudtl.dat',
	'libEGL.dll',
	'libexif.dll',
	'libGLESv2.dll', 
	'natives_blob.bin',
	'node.dll',
	'nw.exe',
	'nw.dll',
	'nw_100_percent.pak',
	'nw_200_percent.pak',
	'nw_elf.dll',
	'resources.pak',
	'snapshot_blob.bin',
	'locales'
]
But the application crashes, so I'm missing something.

**Comment by adamhurst** [comment]
There is a fix here: https://github.com/nwjs/nw-builder/issues/320

**Comment by adam-lynch** [comment]
This is sorted now sorry. Grab the latest version. Thanks for reporting.
