### ISSUE TITLE
updating grunt version in package.json

### ISSUE THREAD

**Issue by artynet** [nwjs/grunt-nw-builder#150]
I think that the minimum version of **grunt** should be updated as dependecy since it is not compatible with the latest release of **grunt-cli** (which requires grunt v1.0.1). I get this error :

```
npm WARN grunt-nw-builder@2.0.0 requires a peer of grunt@~0.4.2 but none was installed
```

my main set up is running node v0.10.38 and npm v3.8.6 (the latest version). However, I also tried with the latest LTS and Stable version of Node.Js (v4.4.2 and v5.10.1) getting the same issue....

Regards, Arturo

**Comment by logitron** [comment]
+1 - Having similar issues with the grunt version not being up-to-date.

**Comment by LeonardLaszlo** [comment]
+1

**Comment by rejas** [comment]
+1
