### ISSUE TITLE
No console output for scripts

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [nwjs/grunt-nw-builder#153]
I use the following command `nwbuild -r .`

It executes and displays my webkit app successfully. 
This is the info to my console:
```

Latest Version: v0.15.0-beta2
Using v0.15.0-beta2
Create cache folder in /usr/local/lib/node_modules/nw-builder/cache/0.15.0-beta2
Using cache for: osx64
Launching App
App exited with code 0
```
It does not display any of the console logs I have placed in the app. I cannot debug my app.

**Comment by adam-lynch** [comment]
Newer NW.js versions and alpha/beta builds weren't supported until today. Please try again. It should be fine. Thanks.
