### ISSUE TITLE
Version 2.0.3 is incompatible with Grunt 0.4.5 while Version 2.0.2 isn't

### ISSUE THREAD

**Issue by Skuldur** [nwjs/grunt-nw-builder#155]
Our project uses Grunt 0.4.5 (for reason we will not divulge), the bump to version 2.0.3 made all of our builds start failing (since 2.0.3 requires Grunt 1.0.1, but the previous version (<=2.0.2) supported Grunt 0.4.5) and now we have to modify all our products/branches to use 2.0.0 instead of latest in ^2.0.0

Shouldn't this change (making grunt-nw-builder) have been a minor/major update instead of a patch update since it causes incompatibility issues?

**Comment by edysegura** [comment]
We are facing this same issue!

**Comment by adam-lynch** [comment]
You're right. I'm sorry about this.
