### ISSUE TITLE
NW Build flavour reference: normal or SDK in options

### ISSUE THREAD

**Issue by Saravanan90** [nwjs/grunt-nw-builder#156]
How to specify the nw build flavour in options? I believe SDK build is generated by default. How to get normal build for production?

https://github.com/nwjs/nw.js/wiki/Build-Flavors

**Comment by Saravanan90** [comment]
Can somebody help me on this issue?

**Comment by adam-lynch** [comment]
We're close to adding support for this in https://github.com/nwjs/nw-builder and once we do, I'll update this project.

**Comment by adam-lynch** [comment]
3.1.0 has support for this now, see https://github.com/nwjs/grunt-nw-builder/releases/tag/3.1.0.

**Comment by Saravanan90** [comment]
Thanks  @adam-lynch
