### ISSUE TITLE
Mac app crashes with nw v0.22.x onwards

### ISSUE THREAD

**Issue by Saravanan90** [nwjs/grunt-nw-builder#161]
https://github.com/nwjs-community/nw-builder/blob/master/CHANGELOG.md#old-format

As per the above link, many updates have been released in `nw-builder` repo but respective releases aren't made in the grunt plugin

Due to which Mac apps are crashing with nw.js `v0.22.x` onwards.

Please update the plugin as well. @adam-lynch Thanks

**Comment by Saravanan90** [comment]
@adam-lynch I have updated the `nw-builder` version in `package.json` and raised PR https://github.com/nwjs/grunt-nw-builder/pull/162. Kindly merge

**Comment by broken** [comment]
+1
I ran into the need for the 3.2.1 fix for nw22+ mentioned in https://github.com/nwjs-community/nw-builder/issues/443
