### ISSUE TITLE
Flash plugin cannot load after grunt_nw_builder package

### ISSUE THREAD

**Issue by chiangandy** [nwjs/grunt-nw-builder#163]
After I use grunt_nw_builder to package my application, but app cannot load flash sucess in flash page, but if  Gruntfile.json set zip:false, flash can be success loaded. However, I really want to zip my script in my package. Does anyone know how to solve it ?

package.json:
---------------
{
  "main": "index.html",
  "name": "ub8",
  "description": "ub8 Client App",
  "version": "1.0.3",
  "keywords": [
    "ub8",
    "UB8"
  ],
  "window": {
    "icon": "icons/logo.png",
    "toolbar": true,
    "width": 1366,
    "height": 768,
    "frame": true,
    "resizable": true,
    "title": "yoyo"
  },
  "chromium-args": "--data-path='data/' --enable-application-cache --ppapi-flash-path='plugins/pepflashplayer.dll' --ppapi-flash-version=21.0.0.213",
  "dom_storage_quota": 10240,
  "webkit": {
    "page-cache": true,
    "java": true,
    "plugin": true
  },
  "ua": "PLATFORM"
}

and Gruntfile.json
-------------------
'use strict';

module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        nwjs: {
            options: {
                platforms: ['win32','osx64'],
                zip: false,
                buildDir: './builds',
                winIco: 'icons/install_icon.ico',
                macIcns: 'icons/install_icon.icns',
                version:'0.14.7'
                , flavor: 'normal'
            },
            src: ['./public/**/*']
        }
    });
    grunt.loadNpmTasks('grunt-nw-builder');
    grunt.registerTask('default', ['nwjs']);
};

**Comment by ayushmxn** [comment]
Closing this since Flash has reached the [end of it's life](https://www.adobe.com/products/flashplayer/end-of-life.html).
