### ISSUE TITLE
nw-builder won't start

### ISSUE THREAD

**Issue by cynpar2** [nwjs/grunt-nw-builder#164]
Hi all, 

It's my first time working with exe compiler and I have a lot a trouble. I'm using nw-builder to compile my .exe. What I want to compile is a micro website (app style)  that is base code in javascript loading and unloading with ajax. 

First of all, everything an intall  my node module it installs 200 files. Is that normal ?

Second of all, when I do succeed to complie the exe  my app won't start. I'm using a lot a proxy and  every time see the sequence  it look like it block there. Could it be the problem ? 

Thanks in advance

**Comment by ayushmxn** [comment]
Let me know if you're still having this issue. Closing this for now.
