### ISSUE TITLE
Win32 build stuck forever

### ISSUE THREAD

**Issue by ananthdp** [nwjs/grunt-nw-builder#168]
This is my nwjs config file.

```
module.exports = {
  prod: {
    options: {
      flavor: 'sdk',
      version: '0.70.1',
      zip: true,
      cacheDir: '../../.nwcache',
      platforms: ['win32'],
      winIco: 'outputs/generated/res/images/icon-128.png',
      appName: '<%=manifest.filePrefix%>-<%=manifest.version%>',
      buildDir: 'outputs/publish'
    },
    src: ['outputs/generated/**/*']
  }
};
```

It's stuck at the create release step. Is there a way to log the steps so that I can figure which step it is exactly stuck at? Also, I have been able to generate the osx64 build the same way pretty easily but no luck with win32.

**Comment by ayushmanchhabra** [comment]
@ananthdp Apologies for the late response. Please try updating to v4.0.0-beta.2 and follow the docs. I'm closing this for now. If there is any problem, ping me here and I'll be happy to reopen.
