### ISSUE TITLE
Re-downloading nodewebkit every time i run the grunt command

### ISSUE THREAD

**Issue by lpetrov** [nwjs/grunt-nw-builder#26]
Not sure why, but every time i run the grunt command its redownloading the .tar.gz packages from s3.
My assumption is that the command should check first the cache/ folder for any existing archives, before re-downloading everything again.

So, am I doing something wrong or i misunderstood the purpose of the cache/ folder  ? :)

Cheers,
L

**Comment by adam-lynch** [comment]
@micksatana ok, thanks

**Comment by sergiomb2** [comment]
Hi, I think this happens on Fedora 21 with system node v0.10.36 , when try build packages under a chroot with mock comand : 
  
    mock -r fedora-21-x86_64 --no-clean  --rebuild pdemo-0.1.20150712git7212f67.fc21.src.rpm

Before begin nmp install is untar all cache but  

    + grunt nodewebkit

Always download node-webkit 

    Running "nodewebkit:src" (nodewebkit) task
    Downloading: http://get.popcorntime.io/nw/v0.12.1/node-webkit-v0.12.1-linux-x64.tar.gz

Any suggestion for grunt nodewebkit use the cache file instead download it or even grunt nodewebkit work without networking ? 

Thanks
