### ISSUE TITLE
Add support for native modules/nw-gyp

### ISSUE THREAD

**Issue by omnidan** [nwjs/grunt-nw-builder#42]
I would like to be able to use a native (C/C++) module. (This, to be exact: https://github.com/nodegit/nodegit)

In order to do this, you need to do a bunch of stuff to make it work with node-webkit: https://github.com/rogerwang/node-webkit/wiki/Using-Node-modules#3rd-party-modules-with-cc-addons

It would be very nice if this builder supported it, because I need it for one of my projects (https://github.com/omnidan/git-leaf).

Edit: I just added grunt-node-webkit-builder support to git-leaf and tried to build it. It works fine on the platform I built it on, but not on windows (it runs, takes a long time to start though - probably timeout while trying to load the lib - and then it can't load a git project, because the lib is missing). Getting `Uncaught Error: %1 is not a valid Win32 application.
` from module.js. So right now, this builder just ignores the native modules.

Note: This might be a duplicate of #41

**Comment by ayushmxn** [comment]
Can open again if there is interest.
