### ISSUE TITLE
Add ability to selectively override package.json using object

### ISSUE THREAD

**Issue by gouldingken** [nwjs/grunt-nw-builder#83]
It would be useful to be able to selectively override package.json properties using an object with the same structure as package.json.

Currently one can override certain properties such as app_name and app_version, but it would provide far more flexibility to be able to define any package.json property for each grunt task.

For example, this object would allow one to switch on or off the toolbar under certain situations. 
```
{
  "window": {
    "toolbar": false
  }
}
```

**Comment by jan4dev** [comment]
Would be very useful. Fortunately, there is grunt to help in the meantime.

**Comment by adam-lynch** [comment]
Don't know how I didn't see this issue until now but did you all see the [platform overrides feature](https://github.com/mllrsohn/grunt-node-webkit-builder#platformoverrides)? I know it's not exactly what you asked for but it might help.
