### ISSUE TITLE
Bug copy files

### ISSUE THREAD

**Issue by Fridus** [nwjs/grunt-nw-builder#84]
My src:
```
[ 'lib/**',
  './node_modules/.../**/*',
  './node_modules/.../**/*',
  ...
 ]
```
Problem is in [this line](https://github.com/mllrsohn/grunt-node-webkit-builder/blob/master/tasks/lib/utils.js#L56-L58)
The `package.json` is in directory `lib/`. So, when it copy node modules, some wrong path:
`./node_modules/glob/node_modules/minimatch/node_modules/lru-cache/lib/lru-cache.js`
to
`./node_modules/glob/node_modules/minimatch/node_modules/lru-cache/lru-cache.js`

**Comment by adam-lynch** [comment]
Sorry no one replied to this until now. It's non-standard to have the `package.json` anywhere but the root. I'm going to close. Correct me if I'm wrong.
