### ISSUE TITLE
Add the ability to sign the mac application

### ISSUE THREAD

**Issue by steffenmllr** [nwjs/grunt-nw-builder#9]
Would be great if the app get's signed on build as in https://github.com/rogerwang/node-webkit/issues/616

https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

**Comment by ayushmxn** [comment]
> @tommoor There are so many annoying tasks besides actually building the app, such as creating icons, creating shortcuts for executables and so on. So I feel like `grunt-node-webkit-builder` is the opportunity to make the process more streamlined. So huge 👍 to this feature.

👋 New maintainer here. I basically agree this except I think this should be integrated into the `nw-builder` (signing for Mac, Windows, Linux that is) and used by the grunt plugin.

**Comment by tharatau** [comment]
Tracking in upstream https://github.com/nwutils/nw-builder/issues/763

Would be great if someone wants to create a PR to speed this feature along!
